import type { StylePreset } from "./types";

export const VARIANT_VOCABULARY = {
  title: ["block", "center-serif", "gradient-band"],
  heading: [
    "number-badge",
    "left-color-bar",
    "plain-bold",
    "chapter-badge",
    "gradient-underline",
    "block-fill",
    "center-ornament",
  ],
  quote: ["center-large-text", "left-line", "large-quote-card", "golden-card", "corner-tag"],
  list: ["minimal-dot", "number-circle-card", "arrow-accent", "card-items"],
  emphasis: ["primary-bold", "highlight", "underline-accent"],
  divider: ["blank-space", "thin-gray-line", "dotted", "ornament", "gradient-line"],
  image: ["caption-frame"],
} as const;

export const VARIANT_LABELS = {
  heading: {
    "number-badge": "序号章（自动编号）",
    "left-color-bar": "左侧色条",
    "plain-bold": "无装饰加粗",
    "chapter-badge": "章节徽标（自动编号）",
    "gradient-underline": "荧光衬底",
    "block-fill": "色块填充",
    "center-ornament": "居中花饰",
  },
  quote: {
    "center-large-text": "居中大字",
    "left-line": "细线引用",
    "large-quote-card": "大引号卡",
    "golden-card": "金句卡",
    "corner-tag": "角标卡片",
  },
  list: {
    "minimal-dot": "极简圆点",
    "number-circle-card": "圆号卡片",
    "arrow-accent": "箭头强调",
    "card-items": "卡片列表",
  },
  divider: {
    "blank-space": "留白",
    "thin-gray-line": "细灰线",
    dotted: "虚线",
    ornament: "装饰符",
    "gradient-line": "渐变线",
  },
} as const;

export const stylePresets: StylePreset[] = [
  {
    id: "magazine_essay",
    name: "杂志随笔",
    moods: ["情感", "观点", "故事"],
    palette: {
      primary: "#2F3437",
      secondary: "#F3F5F6",
      bg: "#FFFFFF",
      textMain: "#24282B",
      textSub: "#8B9298",
      accent: "#6C7A86",
    },
    typography: {
      titleSize: "24px",
      h2Size: "18px",
      bodySize: "15px",
      lineHeight: 1.95,
      letterSpacing: "0px",
      firstLetterDrop: true,
    },
    rhythm: {
      paragraphGap: "20px",
      sectionGap: "34px",
      contentPadding: "0 6px",
      align: "left",
    },
    components: {
      title: { variant: "center-serif" },
      heading: { variant: "underline-line" },
      quote: { variant: "large-quote-card" },
      list: { variant: "minimal-dot" },
      emphasis: { variant: "primary-bold" },
      divider: { variant: "thin-gray-line" },
      image: { variant: "caption-frame" },
    },
    decorations: {
      header: "fine-line",
      footer: null,
      sectionOrnament: null,
    },
  },
  {
    id: "listicle_cards",
    name: "干货清单",
    moods: ["干货", "教程", "盘点"],
    palette: {
      primary: "#2B6CB0",
      secondary: "#E8F0FB",
      bg: "#FFFFFF",
      textMain: "#2F3338",
      textSub: "#8A8F98",
      accent: "#2B6CB0",
    },
    typography: {
      titleSize: "22px",
      h2Size: "17px",
      bodySize: "15px",
      lineHeight: 1.85,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "16px",
      sectionGap: "26px",
      contentPadding: "0 2px",
      align: "left",
    },
    components: {
      title: { variant: "block" },
      heading: { variant: "left-color-bar" },
      quote: { variant: "card" },
      list: { variant: "number-circle-card" },
      emphasis: { variant: "highlight-bg" },
      divider: { variant: "dot-line" },
      image: { variant: "rounded-shadow" },
    },
    decorations: {
      header: null,
      footer: "follow-card",
      sectionOrnament: "number",
    },
  },
  {
    id: "social_bubble",
    name: "轻松社交",
    moods: ["日常", "种草", "随聊"],
    palette: {
      primary: "#0F766E",
      secondary: "#E7F7F3",
      bg: "#FFFFFF",
      textMain: "#26312F",
      textSub: "#7C8B87",
      accent: "#F97316",
    },
    typography: {
      titleSize: "22px",
      h2Size: "17px",
      bodySize: "15px",
      lineHeight: 1.78,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "14px",
      sectionGap: "24px",
      contentPadding: "0 4px",
      align: "left",
    },
    components: {
      title: { variant: "friendly-title" },
      heading: { variant: "icon-prefix" },
      quote: { variant: "bubble" },
      list: { variant: "check-card" },
      emphasis: { variant: "soft-marker" },
      divider: { variant: "round-dots" },
      image: { variant: "rounded" },
    },
    decorations: {
      header: "small-icon-row",
      footer: "soft-follow-card",
      sectionOrnament: "dot",
    },
  },
  {
    id: "business_brief",
    name: "商务简报",
    moods: ["职场", "行业", "通知", "资讯"],
    palette: {
      primary: "#1F4E79",
      secondary: "#EEF2F5",
      bg: "#FFFFFF",
      textMain: "#20262C",
      textSub: "#7B8490",
      accent: "#3B82A0",
    },
    typography: {
      titleSize: "22px",
      h2Size: "17px",
      bodySize: "15px",
      lineHeight: 1.82,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "15px",
      sectionGap: "24px",
      contentPadding: "0 2px",
      align: "left",
    },
    components: {
      title: { variant: "brief-title" },
      heading: { variant: "left-color-bar" },
      quote: { variant: "gray-info-block" },
      list: { variant: "aligned-row" },
      emphasis: { variant: "primary-bold" },
      divider: { variant: "gradient-line" },
      image: { variant: "plain-caption" },
    },
    decorations: {
      header: null,
      footer: "summary-card",
      sectionOrnament: "bar",
    },
  },
  {
    id: "warm_centered",
    name: "走心温暖",
    moods: ["情感", "治愈", "节日"],
    palette: {
      primary: "#B45337",
      secondary: "#F8EEE9",
      bg: "#FFFFFF",
      textMain: "#372D2A",
      textSub: "#9A8279",
      accent: "#D97757",
    },
    typography: {
      titleSize: "23px",
      h2Size: "17px",
      bodySize: "15px",
      lineHeight: 2,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "22px",
      sectionGap: "36px",
      contentPadding: "0 10px",
      align: "center",
    },
    components: {
      title: { variant: "center-soft" },
      heading: { variant: "small-centered-label" },
      quote: { variant: "center-large-text" },
      list: { variant: "soft-card-list" },
      emphasis: { variant: "warm-underline" },
      divider: { variant: "wave-line" },
      image: { variant: "soft-frame" },
    },
    decorations: {
      header: "soft-ornament",
      footer: "warm-follow-card",
      sectionOrnament: "wave",
    },
  },
  {
    id: "knowledge_explainer",
    name: "知识科普",
    moods: ["科普", "解释", "教程"],
    palette: {
      primary: "#256D85",
      secondary: "#E8F6F8",
      bg: "#FFFFFF",
      textMain: "#253034",
      textSub: "#72848A",
      accent: "#2F9EAA",
    },
    typography: {
      titleSize: "22px",
      h2Size: "17px",
      bodySize: "15px",
      lineHeight: 1.86,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "16px",
      sectionGap: "28px",
      contentPadding: "0 4px",
      align: "left",
    },
    components: {
      title: { variant: "science-title" },
      heading: { variant: "icon-prefix" },
      quote: { variant: "term-card" },
      list: { variant: "step-flow" },
      emphasis: { variant: "term-highlight" },
      divider: { variant: "label-line" },
      image: { variant: "diagram-frame" },
    },
    decorations: {
      header: "topic-strip",
      footer: "source-note",
      sectionOrnament: "step",
    },
  },
  {
    id: "minimal_editorial",
    name: "极简克制",
    moods: ["深度", "高级感", "长文"],
    palette: {
      primary: "#111111",
      secondary: "#F4F4F4",
      bg: "#FFFFFF",
      textMain: "#171717",
      textSub: "#737373",
      accent: "#111111",
    },
    typography: {
      titleSize: "25px",
      h2Size: "18px",
      bodySize: "15px",
      lineHeight: 1.98,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "21px",
      sectionGap: "38px",
      contentPadding: "0 8px",
      align: "left",
    },
    components: {
      title: { variant: "heavy-minimal" },
      heading: { variant: "plain-bold" },
      quote: { variant: "left-line" },
      list: { variant: "minimal-dot" },
      emphasis: { variant: "primary-bold" },
      divider: { variant: "blank-space" },
      image: { variant: "plain-caption" },
    },
    decorations: {
      header: null,
      footer: null,
      sectionOrnament: null,
    },
  },
  {
    id: "classic_chinese",
    name: "国风雅致",
    moods: ["文化", "传统", "文艺"],
    palette: {
      primary: "#9F2F24",
      secondary: "#F5F0E8",
      bg: "#FFFFFF",
      textMain: "#2F2925",
      textSub: "#8B7C70",
      accent: "#B84A3C",
    },
    typography: {
      titleSize: "24px",
      h2Size: "18px",
      bodySize: "15px",
      lineHeight: 2,
      letterSpacing: "0px",
      firstLetterDrop: false,
    },
    rhythm: {
      paragraphGap: "20px",
      sectionGap: "34px",
      contentPadding: "0 8px",
      align: "left",
    },
    components: {
      title: { variant: "serif-seal" },
      heading: { variant: "vertical-line" },
      quote: { variant: "calligraphy-quote" },
      list: { variant: "seal-number" },
      emphasis: { variant: "red-underline" },
      divider: { variant: "seal-divider" },
      image: { variant: "paper-frame" },
    },
    decorations: {
      header: "red-seal",
      footer: "classic-note",
      sectionOrnament: "seal",
    },
  },
];

export const defaultStylePreset = stylePresets[1];
